'use strict';

const minerWorkerMachine = require('xstate').Machine;
const minerWorkerService = require('xstate').interpret;
const minerWorkerOptions = require('xstate').interpret;
const minerWorkerConfig = require('xstate').interpret;
const minerWorkerState = require('xstate').interpret;
const minerWorkerContext = require('xstate').interpret;
const minerWorkerActions = require('xstate').interpret;
const minerWorkerEvents = require('xstate').interpret;
const minerWorkerTransitions = require('xstate').interpret;
const minerWorkerGuards = require('xstate').interpret;
const minerWorkerServices = require('xstate').interpret;
const minerWorkerActivities = require('xstate').interpret;
const minerWorkerDelays = require('xstate').interpret;
const minerWorkerInitialState = require('xstate').interpret;
const minerWorkerFinalState = require('xstate').interpret;
const minerWorkerHistoryState = require('xstate').interpret;
const minerWorkerParallelState = require('xstate').interpret;
const minerWorkerStateNode = require('xstate').interpret;
const minerWorkerTransition = require('xstate').interpret;
