//74. getWalletEncryptWallet
//75. getWalletGetAccount
//76. getWalletGetAccountAddress
//77. getWalletGetAddressesByAccount
//78. getWalletGetAddressByLabel
//79. getWalletGetAddressInfo
//80. getWalletGetBalance
//81. getWalletGetNewAddress
//82. getWalletGetRawChangeAddress
//83. getWalletGetReceivedByAccount
//84. getWalletGetReceivedByAddress
//85. getWalletGetTransaction
//86. getWalletGetUnconfirmedBalance
//87. getWalletGetWalletInfo
//88. getWalletImportAddress
//89. getWalletImportMulti
//90. getWalletImportPrivKey
//91. getWalletImportPrunedFunds
//92. getWalletImportPubKey
//93. getWalletImportWallet
//94. getWalletKeyPoolRefill
//95. getWalletListAccounts
//96. getWalletListAddressGroupings
//97. getWalletListLabels
//98. getWalletListLockUnspent
//99. getWalletListReceivedByAccount
//100. getWalletListReceivedByAddress
//101. getWalletListSinceBlock
//102. getWalletListTransactions
//103. getWalletListUnspent
//104. getWalletListWallets
//105. getWalletLockUnspent
//106. getWalletLockWallet
//107. getWalletRemovePrunedFunds
//108. getWalletRescanBlockchain
//109. getWalletSendMany
//110. getWalletSendToAddress
//111. getWalletSetAccount
//112. getWalletSetLabel
//113. getWalletSetTxFee
//114. getWalletSignMessage
//115. getWalletSignRawTransaction
//116. getWalletUnloadWallet
//117. getWalletWalletCreateFundedPsbt
//118. getWalletWalletLock
//119. getWalletWalletPassphrase
//120. getWalletWalletPassphraseChange
//121. getWalletWalletProcessPsbt
//122. getWalletWalletCreateFundedPsbt
//123. getWalletWalletLock
//124. getWalletWalletPassphrase
//125. getWalletWalletPassphraseChange
//126. getWalletWalletProcessPsbt
//127. getWalletZapWalletTxes